[package]
name = "abstract"
edition = "2021"

[dependencies]
lexer = { workspace = true }
ast = { workspace = true }

[workspace]
members = ["lexer", "ast", "lsp-server", "macros"]
default-members = ["lexer"]

[workspace.dependencies]
macros = { path = "macros" }
lexer = { path = "lexer" }
ast = { path = "ast" }
